baseURL = "https://biodms.org/"
languageCode = "en-us"
title = "Biomedical Data Management Systems | Workshop @ VLDB 2026"
theme = "cotton-sky"

[markup]
  [markup.goldmark]
    renderer.unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true
  logo = "images/logo-type-horizontal.png"

[menu]
  [[menu.main]]
    name = "Workshop"
    url = "/"
    pre = ""
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    pre = "blog"
    weight = 20
